language: python
python:
  - "2.7"
install:
  - pip install coverage
  - python setup.py install
script:
  - coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash)
