language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install codecov
  - sudo python setup.py install
script:
  - coverage run tests/test_coverage.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
